config/routes.rb
Chscodes::Application.routes.draw do

  resources :stories do 
    resources :comments
    member do 
      post 'up'
      post 'down'
    end
  end
  

  devise_for :users
  
  root :to => 'stories#index'
  match '/index', to: 'stories#index'
  match '/submit', to: 'stories#new'
  match '/latest', to: 'stories#latest'
  match '/profile', to: 'profile#show'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return false if user.nil?
    can :update, Story do |story|
      story.user_id == user.id
    end
    can :destroy, Story do |story|
      story.user_id == user.id
    end

    can :update, Comment do |story|
      comment.user_id == user.id
    end
    can :destroy, Comment do |story|
      comment.user_id == user.id
    end
    
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  attr_accessible :body
end

app/models/gravatar_profile.rb
class GravatarProfile
  attr_accessor :name, :photo, :url
  def initialize(email)
    email_hash = Digest::MD5.hexdigest(email)
    json = RestClient.get("http://www.gravatar.com/#{email_hash}.json")
    full_profile = JSON.parse(json)
    first_entry = full_profile['entry'].first
    @name, @photo, @url = first_entry['displayName'], first_entry['photos'].first['value'], first_entry['profileUrl']
  end
  
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  attr_accessible :body, :title, :url
  
  validates :title, :presence => true
  validates :url, :presence => true, :if => "body.blank?"
  validates :body, :presence => true, :if => "url.blank?"
  
  scope :latest, :order => 'created_at desc', :limit => 50
end

app/models/story_observer.rb
class StoryObserver < ActiveRecord::Observer
  observe :story
  
  def after_save(story)
    puts 'Post me to Twitter'
    begin
      Twitter.update(story.title)
    rescue 
      Rails.logger.error '************************* Twitter Update Failed'
    end

    true

  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :latest]
  
  def new 
    @story = Story.find(params[:story_id])
    @comment = @story.comments.build
  end
  
  def create
    @story = Story.find(params[:story_id])
    @comment = @story.comments.build(params[:comment])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: 'Successfully submitted comment'}
      else
        format.html { render 'new' }
      end
    end
  end
  
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def show
    @profile = GravatarProfile.new(current_user.email)
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :latest]
  def index
    @stories = Story.limit(50).all
  end
  
  def new
    @story = Story.new
  end
  
  def create
    @story = Story.new(params[:story])
    @story.user = current_user
    respond_to do |format|
      if @story.save
        format.html { redirect_to root_path, 
          notice: 'Successfully submitted course'}
      else
        format.html { render action: 'new' }
      end
    end
  end
  
  def latest
    @stories = Story.latest
    respond_to do |format|
      format.rss { render :layout => false }
      format.html
    end
  end
  
  def show
    @story = Story.find(params[:id])  
  end
  
  
  def edit
    @story = Story.find(params[:id])
  end
  
  def update
    @story = Story.find(params[:id])
    respond_to do |format|
      if @story.update_attributes(params[:story])  
        format.html { redirect_to root_path, notice: 'Successfully updated course'}
      else
        format.html { render 'edit' }
      end
    end
  end
  
  def destroy
    Story.find(params[:id]).destroy
    redirect_to root_path, notice: 'Successfully removed course'
    
  end
  
  def up
    @story = Story.find(params[:id])
    up = @story.up.nil? ? 1 : @story.up + 1
    @story.update_attribute('up', up)
    redirect_to root_path, notice: 'Successfully voted up on course'
  end
  
  def down
    @story = Story.find(params[:id])
    down = @story.down.nil? ? 1 : @story.down + 1
    @story.update_attribute('down', down)
    redirect_to root_path, notice: 'Successfully voted down on course'
    
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/stories_helper.rb
module StoriesHelper

  def story_link(story)
    story.url.blank? ? story_path(story) : story.url
  end
  
  def story_link_url(story)
    story.url.blank? ? story_url(story) : story.url
  end
  
end

app/views/comments/new.html.erb
<h1>New Comment for <%= @story.title %></h1>
<%= form_for [@story, @comment] do |f| %>
  <fieldset>
    <%= f.label :body, "Comment" %>
    <%= f.text_area :body %>
  </fieldset>
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chscodes" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Chscodes</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Top", root_path  %></li>
              <li><%= link_to "Latest", "/latest"  %></li>
              <li><%= link_to "Submit", "/submit"  %></li>
              <li><%= link_to "RSS", "/latest.rss"  %></li>
              
              <% if user_signed_in? %>
                <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to 'Sign In', new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9 offset2">
              <% if flash[:notice] %>
                <div class="alert-message notice">
                  <%= content_tag :div, flash[:notice] %>
                </div>
              <% end %>
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/stories/_form.html.erb
<%= form_for @story, :html => { :class => 'well'} do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'span6', :placeholder => 'enter descriptive title' %>
  </fieldset>
  <fieldset>
    <%= f.label :url %>
    <%= f.text_field :url, :class => 'span6', :placeholder => 'http://www.foo.com' %>
  </fieldset>
  <fieldset>
    <%= f.label :body, 'Text' %>
    <%= f.text_area :body, :class => 'span6', :rows => 5 %>
  </fieldset>
  <%= f.submit 'Submit' %>
<% end %>

app/views/stories/_story.html.erb
<li>
  <%= link_to story.title, story_link(story) %>
  <% if can? :update, story %>
    <%= link_to 'Edit', edit_story_path(story), :class => 'btn' %>
  <% end %>
  <% if can? :destroy, story %>  
    <%= link_to 'Remove', story_path(story), :method => :delete, :confirm => 'Are you sure?', :class => 'btn' %>
  <% end %>
  <%= link_to 'new comment', new_story_comment_path(story) %>
  <%= link_to "comments (#{story.comments.count})", story_path(story) %>
  <%= link_to "Vote Up", up_story_path(story), :method => :post  %>
  <%= link_to "Vote Down", down_story_path(story), :method => :post %>
  <p>
    <label>Votes</label>
    <%= "up #{story.up || 0} down #{story.down || 0}"  %>
  </p>
</li>

app/views/stories/edit.html.erb
<h1>Edit Course</h1>
<%= render 'form' %>

app/views/stories/index.html.erb
<h1>Top Courses</h1>
<ul>
  <%= render @stories %>
</ul>

app/views/stories/latest.html.erb
<h1>Latest Courses</h1>
<ul>
  <%= render @stories %>
</ul>

app/views/stories/new.html.erb
<h1>Submit Course</h1>
<%= render 'form' %>

app/views/stories/show.html.erb
<h1>Show Course</h1>
<h2><%= @story.title %></h2>
<%= @story.body %>
<hr />
<%= link_to 'Back', root_path %>